# sudo: required
language: ruby
rvm:
  - 2.3
  - 2.4
env:
  - RAILS_ENV=test
install:
  - bundle install --binstubs --path vendor/bundle
script:
  - bundle exec rake setup:local['test']
  - bundle exec rake db:migrate
  - bundle exec rspec
addons:
  code_climate:
    repo_token:
      secure: qYKHiwxsKBXvLBmS1oitGCaE1TYJhipsN9D0x81FSLOULE08zNpWKpDUYqiYlOel8lKFhXeFbOGPesf4HgvEq3mGELdvJe059gh3slPtmUSBtsD4b1nOdYEUElbjYlmhdVS+1Yi5kJ7g/sU4bTeLrgNna9pr1jQppgugeIJhvomedILqfRAwqrbaTH40EcqrrcmsHW+tZwPhsSm6bROwEfj6RHZabLU7giUmGA8maxVzgDVpV8Hozq6XVCFlzNqVR8tkpjlg2WA6RZvdypbzF82pyEiJ7U5tRCC/5qjhFqIopIkoxfU+fILR5pri4G/ohLN/iI6hAJxeBFx3rYwRvuw9OmCEOhTUBfkbq1YWrFIfoAzJveaUaoVysF6Bb0eaKsNkBXyXCxRdqQk7PbhtQT1OpzGyU9zQij2rYUYxGoyS50YxYUK5lbUzVquFcipPzPqgeJZ8Er6X1B04AQfIOgI2UNqHNhWmjW33wR4Bxgp4uEUhA9pXz5ArpIxcZ+Y6Dk4fmnWiGFMXn73iIohINqNMuPrOsdyvc0E/pQ4DIJrX8F2g9uBsQqlQeiDVY2v5JYtpTo2Sv/6xKihg6rdxU5Pt7SwowkdCmCL6CV97Nr7KgKR14/t9gaq4k0sGhi+w3d9pGPuuh8/9vrrLRkYVjKBhVKTcjM92Bafle2oheVg=
after_success:
  - bundle exec codeclimate-test-reporter
