sudo: required
language: ruby
rvm:
  - 2.3.0
  - 2.3.3
install:
  - bundle install --binstubs --path vendor/bundle
script:
  - bundle exec rake db:migrate RAILS_ENV=test
  - bundle exec rspec
addons:
  code_climate:
    repo_token: <token>
# regular test configuration
after_success:
  - bundle exec codeclimate-test-reporter
