version: '2'
services:
  hellorubyvscode:
    build: .
    # To run with the debugger
    command: bundle exec rdebug-ide --host 0.0.0.0 --port 1234 -- bin/rails s -b 0.0.0.0 -p 3000 -e development
    # To run without the debugger
    #command: bundle exec /app/bin/rails s -b 0.0.0.0 -p 3000 -e development
    volumes:
      - .:/app
    ports:
      - "1234:1234"
      - "3000:3000"
      - "26162:26162"
