# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10924932965139efc8b35a522f75a169e369b3a5260c58c4429b1ae1d09ec9c5d10c6040a5c670819e4ef5961a4a1cc80ee21f4d76492f16ca22f596a05c672d

test:
  secret_key_base: 9fa8539b97750cb3e025caea5956aeec23e790254de405f6e4bc896d48c0887230762448c35ae4c4de34edce57e989aa3a28d8501dc0f2ccdf4accd05041e06e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
